name: documentation

on:
  push:
    branches:
      - master
      - feature/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo gem install asciidoctor asciidoctor-pdf rouge

      - name: Setup Boost
        run: |
          REF=${GITHUB_BASE_REF:-$GITHUB_REF}
          BOOST_BRANCH=develop && [ "$REF" == "master" ] && BOOST_BRANCH=master || true
          cd ..
          git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
          cd boost-root
          mkdir libs/synapse
          cp -r $GITHUB_WORKSPACE/* libs/synapse
          git submodule update --init tools/build
          git submodule update --init libs/config
          ./bootstrap.sh

      - name: Create user-config.jam
        run: |
          echo "using asciidoctor ;" > ~/user-config.jam

      - name: Build documentation
        run: |
          cd ../boost-root/libs/synapse/doc
          ../../../b2

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ../boost-root/libs/synapse/doc/html
